# Generated by Django 5.0.7 on 2024-07-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('quartos', models.IntegerField(null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_imoveis.bairro')),
            ],
        ),
    ]
