# Generated by Django 5.0.7 on 2024-08-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('quartos', models.IntegerField(null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_imoveis.bairro')),
            ],
        ),
        migrations.DeleteModel(
            name='Imovel',
        ),
    ]
