# Generated by Django 5.0.7 on 2024-08-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_imoveis', '0002_alter_bairro_bairro_casa_delete_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='quartos',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='valor',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
