# Generated by Django 5.0.7 on 2024-08-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_imoveis', '0003_alter_casa_quartos_alter_casa_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='bairro',
            new_name='nome_bairro',
        ),
    ]
